feat: configurable disk alert threshold
pyroscope-io/pyroscope pull request #1318
Opened 2022-07-28 14:36 UTC by kolesnikovae

2022-07-28 14:38 UTC, kolesnikovae commented on pkg/util/disk/usage_test.go
> +				Expect(u.Available).To(BeNumerically("<", u.Total))
Actually, I'm not 100% if these are reasonable assertions

2022-08-05 09:23 UTC, petethepig commented on pkg/config/config.go
> +	StorageDiskThreshold float64 `def:"5" desc:"percentage of available disk space at which ingestion requests are discarded. Defaults to 5%. Set 0 to disable" mapstructure:"storage-disk-threshold"`
I would call it something a little more explicit. Right now it's unclear from the name what this parameter does.

Maybe `MinFreeSpacePercentage`?

2022-08-05 09:25 UTC, petethepig requested changes
I have two comments:
* if you have less than 10GB of space the minimum space is going to be set pretty low, e.g if you have 5GB disk it's going to be set at 256MB — this is way to low for the system to operate. So I propose that we add another hard limit (e.g say 1GB), and then we take something like `max(1GB, 5%*total space)`
* the naming of the parameter could be better imo, mentioned it in the comments

2022-08-05 10:53 UTC, kolesnikovae commented
> I have two comments:
>
> if you have less than 10GB of space the minimum space is going to be set pretty low, e.g if you have 5GB disk it's going to be set at 256MB — this is way to low for the system to operate. So I propose that we add another hard limit (e.g say 1GB), and then we take something like max(1GB, 5%*total space)
> the naming of the parameter could be better imo, mentioned it in the comments

Fixed

2022-08-07 23:42 UTC, petethepig approved these changes

2022-08-07 23:42 UTC, merged