chore(webapp): timeline chart, removed circles on dataPoints, added crosshair cursor
pyroscope-io/pyroscope pull request #1446
Opened 2022-08-26 13:30 UTC by StasDachinsky

## Brief
- https://github.com/pyroscope-io/pyroscope/issues/1400
## Changes
 - added crosshair cursor
 - removed circles on dataPoints
## Concerns
- I think that simply reducing the line width for line charts is not the best option, and we need to do this dynamically based on the lengths of dataPoints and Apps arrays. Reducing the width looks good for large time periods (and big data), but almost useless for small

https://user-images.githubusercontent.com/23450818/186914561-e0d707d9-6cb9-4f89-baec-28110d336d7b.mov

2022-08-26 13:50 UTC, dogfrogfog commented on webapp/javascript/components/TimelineChart/TimelineChartSelection.ts
> +      return function setCursor(type: string) {
can we use anonymous function here ?

2022-08-26 14:45 UTC, pavelpashkovsky requested changes

2022-08-26 14:45 UTC, pavelpashkovsky commented on webapp/javascript/components/TimelineChart/TimelineChartSelection.ts
> +    function cursor() {
function `cursor`? please add what does this function do to the name. setCursor? changeCursor?

2022-08-26 14:45 UTC, pavelpashkovsky commented on webapp/javascript/components/TimelineChart/TimelineChartSelection.ts
> +      return function (type: string) {
what the point of returning function? can you simplify it?

2022-08-26 14:45 UTC, pavelpashkovsky commented on webapp/javascript/components/TimelineChart/TimelineChartSelection.ts
> +    plot.setCursor = cursor();
can you please make name of this function more informative cursor();

plot.setCursor = setCursor(); ?

2022-08-26 14:48 UTC, pavelpashkovsky commented
@StasDachinsky can you please take a look at 
pyroscope/webapp/javascript/components/TimelineChart/TimelineChartPlugin.ts

at `function bindEvents(plot, eventHolder)` you can add any handlers (or use existing) to it. might be helpful

2022-08-26 16:22 UTC, Rperry2174 commented
/create-server

2022-08-26 16:38 UTC, eh-am reviewed
I don't quite understand why do we need all these changes, if we already support it here https://github.com/pyroscope-io/pyroscope/blob/5788cf9943a579acd35de224537016488a98808f/webapp/sass/profile.scss#L110-L116

I feel like this implementation does more than the trivial impl above, can you just explain it what it does?

Also, if we are going with this route, we should remove that css I linked above then.

2022-08-26 16:46 UTC, eh-am commented on webapp/javascript/components/TimelineChart/TimelineChartPlugin.ts
> +      if (this.isHover !== isHover) {
```suggestion
      const hasChanged = this.isHover !== isHover;
      if (hasChanged) {
```

a nit, but I found these are clearer to read, any chance to reduce mental overhead is a good idea

2022-08-26 16:46 UTC, eh-am commented on webapp/javascript/components/TimelineChart/TimelineChartSelection.ts
> +  setCursor: (cursor: string) => void;
```suggestion
  setCursor: (cursor: 'grab' | 'crosshair') => void;
```

If possible let's narrow the types as much as possible. By having just `string` thereotically a `setCursor("FOOOOOOO")` is valid, although it's obviously not true.

2022-08-26 16:46 UTC, eh-am commented on webapp/javascript/components/TimelineChart/TimelineChartSelection.ts
> +        if (type && current !== type) {
Why do you have to check `type` is truthy? If it's always truthy we don't need to check it, and if it's not truthy then we need to indicate that in the types (ie `(type: string)` becomes `(type?: string)`)

2022-08-26 16:46 UTC, eh-am commented on webapp/javascript/components/TimelineChart/TimelineChartSelection.ts
> +          $('canvas.flot-overlay').css('cursor', type);
What if there are 2 canvas in the same page?

2022-08-26 16:46 UTC, eh-am commented on webapp/javascript/components/TimelineChart/TimelineChartWrapper.tsx
> +        symbol: () => {}, // function that draw points on the graph
Nice!

2022-08-26 16:47 UTC, eh-am commented on webapp/javascript/components/TimelineChart/TimelineChartSelection.ts
> +          $('canvas.flot-overlay').css('cursor', type);
I wonder if there isn't a way to get the actual element we care about cc @pavelpashkovsky

2022-08-31 03:41 UTC, Rperry2174 commented
/create-server

2022-09-11 22:15 UTC, Rperry2174 approved these changes
LGTM

2022-09-11 22:16 UTC, merged