chore(webapp): Don't show empty series in timeline or table
pyroscope-io/pyroscope pull request #1471
Opened 2022-09-07 12:47 UTC by pavelpashkovsky

## Brief
- https://github.com/pyroscope-io/pyroscope/issues/1464

## Changes
- filter empty series just after they were received from backend and before they get to the redux store
![image](https://user-images.githubusercontent.com/7372044/188881221-d68cf165-d21d-4ec5-88cb-f83747a853f2.png)

## Concerns
-

2022-09-07 13:02 UTC, pavelpashkovsky commented
@eh-am does it make sense to extract this part to the function and add tests?

2022-09-07 13:41 UTC, eh-am requested changes
As you can see, this can be implemented in multiple places, so it's important to understand from a conceptual POV where it belongs to:

* is it a decision on purely the **view** side? if so, let's do it at the component layer/redux selection layer (https://redux.js.org/usage/deriving-data-selectors)
* is it something backend is returning kinda wrong and it should never enter the `frontend layer`? then let's do this processing at the **data service** layer

I personally prefer to leave reducers as thin as possible. Ideally it should just get whatever data the data service layer returned and add to the store.

2022-09-07 13:50 UTC, pavelpashkovsky commented
from task:
>I think we ideally should remove this as close to the api response as possible

If I understand user should see such a data at all, so maybe it needs to be moved on backend side, right? 
cc @eh-am , @Rperry2174

2022-09-07 14:10 UTC, eh-am commented
Or, as a stopgap, to implement it here https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/services/render.ts#L198 using https://github.com/colinhacks/zod#preprocess

2022-09-08 23:03 UTC, Rperry2174 commented
/create-server

2022-09-12 19:09 UTC, Rperry2174 approved these changes
LGTM!

2022-09-12 19:10 UTC, merged