feat: Explore piechart
pyroscope-io/pyroscope pull request #1477
Opened 2022-09-08 14:06 UTC by pavelpashkovsky

## Brief
- https://github.com/pyroscope-io/pyroscope/issues/1420

## Changes
- added PieChart based on tags

2022-09-08 14:11 UTC, eh-am requested changes

2022-09-08 14:11 UTC, eh-am commented on webapp/javascript/pages/TagExplorerView.module.scss
> +.statiscticsBox {
```suggestion
.statisticsBox {
```

2022-09-08 14:11 UTC, eh-am commented on webapp/javascript/pages/tagExplorer/components/PieChart/index.tsx
> +const PieChart = ({ data }: { data: TimelineGroupData[] }) => {
I think this can be a generic/reusable `PieChart` component, and the transformations are done outside it.

2022-09-08 14:27 UTC, pavelpashkovsky commented
/create-server

2022-09-08 16:12 UTC, Rperry2174 commented
Great start!
![image](https://user-images.githubusercontent.com/23323466/189171141-75566b95-8120-4574-9d1a-2b5ccf33ee52.png)

two thoughts:
1. We should change the columns in the table to be:

~Tag name | Event count | avg samples | std deviation samples~
Tag name | avg samples | std deviation samples | total samples |

(removing Event count)

2. We should find a way to deal with when the pie chart has a lot of series or very small slices. Maybe we can look into how other popular libraries do it like [grafana](https://grafana.com/docs/grafana/latest/visualizations/pie-chart-panel/), [D3](https://d3-graph-gallery.com/pie)

One idea is maybe for the pie chart we only show the top 5 series and group everything else into "other" 

wdyt? cc @eh-am @petethepig

2022-09-09 12:58 UTC, pavelpashkovsky commented
In my opinion grouping small slices would be the best solution.

What I found about that:
https://support.microsoft.com/en-us/office/explode-or-expand-a-pie-chart-63284b67-22ea-4960-ab1e-0a3895af68ce

https://chandoo.org/wp/group-small-slices-in-pie-charts/

https://www.addtwodigital.com/add-two-blog/2021/2/13/rule-3-not-too-many-wedges-not-too-few

I think we can show top N, and put the rest of slices under the "Other". But what to do with the "Other"? open on click? How many levels of opening it might have? I would go with 2 levels for first time

2022-09-09 14:13 UTC, pavelpashkovsky commented
![image](https://user-images.githubusercontent.com/7372044/189368961-ca6558bf-0895-40de-ad08-ff057dca1e3c.png)

I pushed POC on condition if we show top 5 results (hide the rest under Other). It would be nice if you `/create-server` and give some feedback. 

I'm thinking that there is another option, we can show first N slices if they take place, for example, 70%, the rest of slices should be hidden under the "Other". We can reach the best result if we can combine these 2 methods, but honestly I can't provide any condition for it :)

2022-09-09 18:27 UTC, Rperry2174 commented
Yeah this one is tricky... Let's try going this route:
![image](https://user-images.githubusercontent.com/23323466/189419044-7d81679b-58c9-4458-bbbc-bc88d1398a8c.png)

And then only show the top X labels (default to something like 3 or 5)

2022-09-12 14:16 UTC, pavelpashkovsky commented
/create-server

2022-09-12 14:40 UTC, pavelpashkovsky commented
/create-server

2022-09-13 11:25 UTC, pavelpashkovsky commented
/create-server

2022-09-14 10:27 UTC, pavelpashkovsky commented
I set threshold value as 0.17, it means, if slice bigger than 17% it will render label, not ideal but my testing shows this is kinda "optimal" value. You can play with this value in 
`webapp/javascript/pages/tagExplorer/components/TotalSamplesChart/PieChart/index.tsx`
![image](https://user-images.githubusercontent.com/7372044/190130164-4483acd4-afff-47ef-82de-12ab0af0202f.png)

2022-09-14 14:55 UTC, Rperry2174 commented
/create-server

2022-09-14 15:36 UTC, Rperry2174 approved these changes
LGTM! I might play around with the sizing of the pie chart but I'll do that separately

2022-09-14 15:36 UTC, merged