fix a few function names on comments
pyroscope-io/pyroscope pull request #1676
Opened 2022-11-04 09:57 UTC by cuishuang

2022-11-04 10:58 UTC, kolesnikovae requested changes
Thank you for the contribution @cuishuang! There is one issue with a removed import – could you check it please?

2022-11-04 10:58 UTC, kolesnikovae commented on pkg/scrape/config/config_http.go
> -	"github.com/mwitkow/go-conntrack"
Must've been removed unintentionally. This import is required

2022-11-04 10:58 UTC, kolesnikovae commented on pkg/util/process/process_unix.go
> +// SendSignal send signal s to the process p.
```suggestion
// SendSignal sends signal s to the process p.
```

2022-11-06 20:43 UTC, Rperry2174 approved these changes
LGTM! Thanks @cuishuang !

2022-11-06 20:44 UTC, merged