Make sidebar links
pyroscope-io/pyroscope pull request #489
Opened 2021-10-31 23:04 UTC by clovis1122

NOTE: this includes changes from https://github.com/pyroscope-io/pyroscope/pull/488, please check that one first!

This PR uses the NavLink component on the sidebar to make these act as links. Because the history state is now managed by a 3rd party, we can safely remove the previous test as well (otherwise we would be basically testing the 3rd party library...).

closes https://github.com/pyroscope-io/pyroscope/pull/488
closes https://github.com/pyroscope-io/pyroscope/issues/305

2021-11-02 04:35 UTC, clovis1122 commented
@eh-am can I get a review for this one too?

2021-11-02 14:15 UTC, eh-am commented
@clovis1122 Thank you again!

Hmm, weird, now the query params aren't being passed between different pages:
This is the main branch
![Peek 2021-11-02 11-12](https://user-images.githubusercontent.com/6951209/139864227-26320d3b-621d-4dbc-95f9-b703d5e2c410.gif)

This is this PR
![Peek 2021-11-02 11-13](https://user-images.githubusercontent.com/6951209/139864356-48a87bd8-239a-4cd0-8d6f-e99d2775944c.gif)

2021-11-04 00:31 UTC, clovis1122 commented
@eh-am whoops! Fixed!

2021-11-04 14:44 UTC, eh-am requested changes
Thank you!

Added few suggestions, super minor, but overall looks great!

2021-11-04 14:44 UTC, eh-am commented on webapp/javascript/components/Sidebar.jsx
> +          to={`/${search}`}
```suggestion
          to={{ pathname: '/', search }}
```

2021-11-04 14:44 UTC, eh-am commented on webapp/javascript/components/Sidebar.jsx
> +          to={`/comparison${search}`}
```suggestion
          to={{ pathname: '/comparison', search }}
```

2021-11-04 14:44 UTC, eh-am commented on webapp/javascript/components/Sidebar.jsx
> +          to={`/comparison-diff${search}`}
```suggestion
          to={{ pathname: '/comparison-diff', search }}
```

2021-11-05 10:51 UTC, clovis1122 commented
Thanks, done!

2021-11-05 13:12 UTC, merged

2021-11-05 17:05 UTC, Rperry2174 commented
This is awesome thanks @clovis1122 !!!