Dropdown component
pyroscope-io/pyroscope pull request #550
Opened 2021-11-18 16:13 UTC by ruslanpascoal2

https://github.com/pyroscope-io/pyroscope/issues/548

Created a dropdown component and a storybook story for it.

2021-11-18 17:53 UTC, eh-am requested changes
Beautiful!

---
(Talking to myself)

I am even thinking bastardizing the submenu to make it become like some kind of explanation like grafana does
![image](https://user-images.githubusercontent.com/6951209/142467544-f67c7426-6c97-4a27-a8bf-d3d5d9ffbe24.png)

2021-11-18 17:53 UTC, eh-am commented on stories/Dropdown.stories.tsx
> +const Template: ComponentStory<any> = (args) => (
```suggestion
const Template: ComponentStory<typeof Dropdown> = (args) => (
```

2021-11-18 17:53 UTC, eh-am commented on stories/Dropdown.stories.tsx
> +} as ComponentMeta<any>;
```suggestion
} as ComponentMeta<typeof Dropdown>;
```

2021-11-18 17:53 UTC, eh-am commented on stories/Dropdown.stories.tsx
> +
Can we have an example where it behaves like a dropdown, where after you select a value, it replaces the "Menu" there?

2021-11-18 22:06 UTC, ruslanpascoal2 commented on stories/Dropdown.stories.tsx
> +} as ComponentMeta<any>;
Forgot to replace the any, sorry

2021-11-19 17:45 UTC, eh-am approved these changes

2021-11-19 17:47 UTC, eh-am commented
I love it! Really nice touch adding the label as Header, so after I pick a value I still know what's the Dropdown for (Otherwise just having the list of elements don't tell me anything).

![Peek 2021-11-19 14-45](https://user-images.githubusercontent.com/6951209/142667882-1d3866b0-e87e-408b-a287-f445b624e962.gif)

2021-11-19 21:16 UTC, petethepig approved these changes
Awesome, thank you for the contribution @ruslanpascoal2 !

2021-11-19 21:19 UTC, merged