fix(frontend): shifted actual data to 5 seconds forward
pyroscope-io/pyroscope pull request #742
Opened 2022-01-19 10:15 UTC by shaleynikov

…fixing almost all issues with selection

Related to:
- https://github.com/pyroscope-io/pyroscope/issues/621
- https://github.com/pyroscope-io/pyroscope/issues/713

2022-01-19 19:55 UTC, petethepig commented on webapp/javascript/components/TimelineChartWrapper.jsx
> +    const flotOptions = {
You're not actually using this one later on line :187


Other than that it looks and works great!

2022-01-19 19:56 UTC, petethepig reviewed
see comments above

2022-01-19 19:57 UTC, petethepig requested changes
see comments above

2022-01-21 17:17 UTC, shaleynikov commented
Now it should be fine :-)

2022-01-21 17:18 UTC, shaleynikov reviewed
Now it uses options provided

2022-01-22 02:32 UTC, petethepig approved these changes
Looks great, thank you!

2022-01-22 02:33 UTC, merged